name: Build and Publish Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload distribution to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
